// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Acknowledger is an autogenerated mock type for the Acknowledger type
type Acknowledger struct {
	mock.Mock
}

// Ack provides a mock function with given fields: tag, multiple
func (_m *Acknowledger) Ack(tag uint64, multiple bool) error {
	ret := _m.Called(tag, multiple)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bool) error); ok {
		r0 = rf(tag, multiple)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Nack provides a mock function with given fields: tag, multiple, requeue
func (_m *Acknowledger) Nack(tag uint64, multiple bool, requeue bool) error {
	ret := _m.Called(tag, multiple, requeue)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bool, bool) error); ok {
		r0 = rf(tag, multiple, requeue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reject provides a mock function with given fields: tag, requeue
func (_m *Acknowledger) Reject(tag uint64, requeue bool) error {
	ret := _m.Called(tag, requeue)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bool) error); ok {
		r0 = rf(tag, requeue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
