// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	consumer "github.com/diegodesousas/go-rabbitmq/consumer"
	mock "github.com/stretchr/testify/mock"
)

// Option is an autogenerated mock type for the Option type
type Option struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Option) Execute(_a0 *consumer.DefaultConsumer) *consumer.DefaultConsumer {
	ret := _m.Called(_a0)

	var r0 *consumer.DefaultConsumer
	if rf, ok := ret.Get(0).(func(*consumer.DefaultConsumer) *consumer.DefaultConsumer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consumer.DefaultConsumer)
		}
	}

	return r0
}
