// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	connection "github.com/diegodesousas/go-rabbitmq/connection"

	mock "github.com/stretchr/testify/mock"
)

// Connection is an autogenerated mock type for the Connection type
type Connection struct {
	mock.Mock
}

// Channel provides a mock function with given fields:
func (_m *Connection) Channel() (connection.Channel, error) {
	ret := _m.Called()

	var r0 connection.Channel
	if rf, ok := ret.Get(0).(func() connection.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(connection.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsClosed provides a mock function with given fields:
func (_m *Connection) IsClosed() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
