name: Development

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

   -  name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

    - name: Install dependencies
      run: go mod download

    - name: Tests
      run: ./gotestsum --format=pkgname --junitfile tests.xml -- -race -covermode=atomic -coverprofile cover.out ./...

    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        files: ./cover.out
        token: ${{ secrets.CODECOV_TOKEN }}