name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Install dependencies
      run: go mod download

    - name: Test
      run: ./gotestsum --format=pkgname --junitfile tests.xml -- -race -covermode=atomic -coverprofile cover.out ./...
